FIND_PATH(DEFAULTS_INCLUDE_DIR defaults.h
    /usr/local/include
)

FIND_LIBRARY(DEFAULTS_LIBRARIES
  NAMES libdefaults.so
  PATHS /usr/local/lib
)
FIND_LIBRARY(DEFAULTS_SETTINGS_LIBRARIES
  NAMES libdefaults_settings.a 
  PATHS /usr/local/lib
)

IF (DEFAULTS_LIBRARIES AND DEFAULTS_INCLUDE_DIR)
  SET(DEFAULTS_FOUND "YES")
ELSE (DEFAULTS_LIBRARIES AND DEFAULTS_INCLUDE_DIR)
  SET(DEFAULTS_FOUND "NO")
ENDIF (DEFAULTS_LIBRARIES AND DEFAULTS_INCLUDE_DIR)

IF (DEFAULTS_FOUND)
  IF (NOT DEFAULTS_FIND_QUIETLY)
    MESSAGE(STATUS "Found DEFAULTS: ${DEFAULTS_LIBRARIES} ${DEFAULTS_SETTINGS_LIBRARIES}")
  ENDIF (NOT DEFAULTS_FIND_QUIETLY)
ELSE (DEFAULTS_FOUND)
  IF (DEFAULTS_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find DEFAULTS library")
  ENDIF (DEFAULTS_FIND_REQUIRED)
ENDIF (DEFAULTS_FOUND)
